config/routes.rb
Rails.application.routes.draw do


    root "users#signup"
    get "/signup" => "users#signup"
    post "/register" => "users#register"
    get "login" => "users#login"
    post "login" => "users#valid"
    get "wel" => "users#wel"
    post "valid" => "users#valid"
    post "logout" => "users#logout"
# get "goal" => "users#goal"
# get "create_goal" => "users#create_goal"


 resources :users
 resources :goals

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user
  has_many :tasks


end

app/models/user.rb
class User < ApplicationRecord
  #validates :email, presence: true
has_many :goals
 belongs_to :user
 has_many :tasks
 belongs_to :goal

























  validates :uname, :password, :email, :address, :phno, presence: true
  validates :email, presence: true, format: /\w+@\w+\.{1}[a-zA-Z]{2,}/
 validates :phno, length: { maximum: 10 }
 validates :phno, numericality: { only_integer: true }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authorize, except: [:signup, :login, :valid, :register]
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/concerns/gif.rb
class GifController < ApplicationController

  before_filter :authorize

  def cool
  end

  def free
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

before_action :set_student, only: [:show, :edit, :update, :destroy]

 def goal
      @goal=Goal.new
  end


  def Your_Goal
      @my_goal=@user.goals
  end

  def new
     @goal=Goal.new
  end

  def update
    respond_to do |format|
      if @goal.update(user_params)
        format.html { redirect_to @goal, notice: 'signup was successfully updated.' }
        format.json { render :show, status: :ok, location: @goal}
      else
        format.html { render :edit }
        format.json { render json:   @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    # binding.pry
     @goal = Goal.new(goal_params)
     @goal.user = current_user
    respond_to do |format|
      if @goal.save
        format.html { redirect_to "/wel", notice: 'goal created!!!!!!!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
    end

   def goal_params
      params.require(:goal).permit(:title, :start_date, :completion_date)
  end



end

app/controllers/sessions_controller.rb
 def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to '/'
    else
    # If user's login doesn't work, send them back to the login form.
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_student, only: [:show, :edit, :update, :destroy]

  def signup

    @user=User.new
    puts "form"
  end
  def login
    @user=User.new
  end

  def valid
       user = User.find_by_email(params[:user][:email])
       password=User.find_by_password(params[:user][:password])
       # binding.pry
     if user && password
        session[:user_id]=user.id
        redirect_to wel_path

      else
          redirect_to  "/signup"
      end
  end

  def Your_Goal
      @my_goal=@user.goals
  end
  def logout
      session[:user_id] = nil
      redirect_to signup_path, :notice => "Logged out"
  end


  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to  @user, notice: 'signup was successfully updated.' }
        format.json { render :show, status: :ok, location:   @user}
      else
        format.html { render :edit }
        format.json { render json:   @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def register
    # binding.pry
     @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to "/login", notice: 'Signup successfully!!!!!!!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :signup }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    end




   def user_params
      params.require(:user).permit(:uname, :email, :address, :phno, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goal_helper.rb
module GoalHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/new.html.erb
<b><i><u><center><font size="500"><font color="green">Goal </font></font></center></u></i></b>
<i><b>create goal</b></i>
  <% session[:current_user] %>
<p align="right"><%= link_to "logout", logout_path, method: :post %></p>


<%= form_for(@goal) do |f| %>

  <table>
  <div class="field">
   <tr><td> <%= f.label :title  %> </td>

   <td>  <%= f.text_field :title, placeholder:"Enter your Goal" %></td></tr>
   </div>

  <div class="field">
    <tr><td> <%= f.label :start_date%></td>

     <td><%= f.text_field :start_date, placeholder:"Enter your Start_date" %></td></tr>
  </div>
  <div class="field">
     <tr><td><%= f.label :completion_date%></td>

     <td><%= f.text_field :completion_date, placeholder:"Enter your expected completion_date" %></td></tr>
  </div>
<div class="actions">

  <tr><td></td><td><%= f.submit "OK" %></td></tr>
  </div>
  </table>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GifVault</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

# added these lines.
<% if current_user %>
  Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
<% else %>
  <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/create_goal.html.erb
<i><b>create goal</b></i>
  <% session[:current_user] %>
<p align="right"><a href="signup">Log out</a></p>

app/views/users/login.html.erb
<b><i><u><center><font size="500"><font color="green"> login </font></font></center></u></i></b>

<p id="notice"><p align="center"><font color="blue"><%= notice %></p></font></p>
<i><b><a href="signup"<font size="50">new user??</b></i></a>

<%= form_for(@user,:url => "/valid") do |f| %>





  <div class="field">
    <%= f.label :Email  %>     :
    <br>
     <%= f.text_field:email,placeholder:"Enter your email" %>
  </div>
<br>
  <div class="field">
    <%= f.label :password%> :
    <br>
     <%= f.text_field :password,placeholder:"Enter your password" %>
  </div>
   <div class="actions">
   <%= f.submit "login" %>


  </div>
<% end %>
<style type="text/css">
body {
  background-color: grey;
}

</style>

app/views/users/signup.html.erb
<b><i><u><center><font size="500"><font color="green"> welcome new user </font></font></center></u></i></b>




<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> Alert!!!!!!!</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>




<style type="text/css">
body {
  background-color: grey;
}

</style>
<p align="center">
<ul>
<i><b>Already registerd??</b></i>
  <li><a href="login"><font size="100">login</font></a></li>

</ul>
</p>


<br>
<br>
<%= form_for(@user, url: register_path) do |f| %>

   <div class="field">
    <%= f.label :uname  %>     :
    <br>
     <%= f.text_field:uname,placeholder:"Enter your user name" %>
  </div>

<br>
  <div class="field">
    <%= f.label :password%> :
    <br>
     <%= f.text_field:password,placeholder:"Enter your password" %>
  </div>
<br>
  <div class="field">
    <%= f.label :address%>  :
    <br>
     <%= f.text_field:address,placeholder:"Enter your address" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :email%>      :
    <br>
    <%= f.text_field:email,placeholder:"enter your email" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :phone_no  %>      :
    <br>
     <%= f.text_field:phno,placeholder:"Enter your Phone no" %>

  </div>
  </p>
  <br>


  <div class="actions">
   <%= f.submit "SIGN UP" %>
  </div>
<% end %>

app/views/users/wel.html.erb
<b><i><u><center><font size="500"><font color="green">welcome </font></font></center></u></i></b>
<b><i><font color="violet"><p align="center"><font size="50">
  create your own Goal!!!!!!!!!!!!!!!!!</p></b></i></font>

  <i><a href="/goals/new">Create your goal</a></i>
  <% session[:current_user] %>

<select>
  <option> :::</option>
  <option> Goal</a></option>
  <option>Contact</option>
  <option>About us</option>
</select>
<style type="text/css">
body {
  background-color: grey;
}

</style>